# Generated by Django 2.2.6 on 2020-01-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0029_remove_t_bill_client_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_bill',
            name='billing_date_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
