# Generated by Django 2.2.6 on 2020-01-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0026_auto_20200128_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_accts',
            name='acct_company',
            field=models.IntegerField(default=1),
        ),
    ]
