# Generated by Django 2.2.6 on 2020-01-29 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0029_auto_20200128_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_accts',
            name='status',
            field=models.CharField(blank=True, default='Active', max_length=10, null=True),
        ),
    ]
